CREATE TABLE games (
    id INTEGER PRIMARY KEY,
    name TEXT,
    description TEXT,
    category TEXT,  
    image TEXT,         
    is_published INTEGER DEFAULT 0
);

INSERT INTO games (id, name, description, category, image, is_published) VALUES (1, 'Number Sequence', 'Test your memory and focus in this fast-paced number sequence challenge! A sequence of numbers will briefly appear on the screen, and your goal is to recall and input the sequence correctly. With each correct answer, the length of the sequence increases, making the game progressively more difficult. How long can you keep up as the numbers become harder to remember?', 'memory', 'https://memcaydiastorage.blob.core.windows.net/games/number-sequence.webp', 1);
INSERT INTO games (id, name, description, category, image, is_published) VALUES (2, 'Reaction Time', 'Your reflexes are of great importance in this challenge. A series of shapes will appear on the screen, and your goal is to click on them as fast as possible. How fast are your reflexes? Put them to the test in this exciting game!', 'speed', 'https://memcaydiastorage.blob.core.windows.net/games/reaction-time.webp', 1);
INSERT INTO games (id, name, description, category, image, is_published) VALUES (3, 'Color Match', 'How well can you differentiate between colors? In this game, you''ll be presented with a color and four options to choose from. Your goal is to select the correct color that matches the one displayed. As you progress, the colors become more similar, making it harder to distinguish between them. Test your color perception and see how many levels you can complete!', 'perception', 'https://memcaydiastorage.blob.core.windows.net/games/color-match.webp', 1);
INSERT INTO games (id, name, description, category, image, is_published) VALUES (4, 'Word Scramble', 'Unscramble the letters and form words in this challenging word game! You''ll be presented with a set of jumbled letters, and your task is to rearrange them to create a valid word. The difficulty increases with each level, as the words become longer and more complex. How many words can you unscramble before time runs out?', 'word', 'https://memcaydiastorage.blob.core.windows.net/games/word-scramble.webp', 0);
INSERT INTO games (id, name, description, category, image, is_published) VALUES (5, 'Word Recall', 'Challenge your memory and attention in this word recall game! You''ll be presented with one word at a time, and your task is to decide whether you''ve seen the word before or not. As the game progresses, more words will be introduced, and you''ll need to rely on your memory to avoid making mistakes. How long can you keep track of the words? Test your recall skills and see how many rounds you can complete!', 'memory', 'https://memcaydiastorage.blob.core.windows.net/games/word-recall.webp', 1);
INSERT INTO games (id, name, description, category, image, is_published) VALUES (6, 'Memory Tile', 'Test your memory and focus in this fast-paced tile memory challenge! A grid of tiles will briefly highlight in a specific pattern before disappearing. Your goal is to recall and select the correct tiles in the right order. With each correct round, the sequence grows longer, making the game progressively more challenging.', 'memory', 'https://memcaydiastorage.blob.core.windows.net/games/memory-tile.webp', 1);